'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class Register

        '''<summary>
        '''form1 control.
        '''</summary>
        Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''lblMessage control.
        '''</summary>
        Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtFirstName control.
        '''</summary>
        Protected WithEvents txtFirstName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtLastName control.
        '''</summary>
        Protected WithEvents txtLastName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtEmail control.
        '''</summary>
        Protected WithEvents txtEmail As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtPassword control.
        '''</summary>
        Protected WithEvents txtPassword As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtConfirmPassword control.
        '''</summary>
        Protected WithEvents txtConfirmPassword As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''btnRegister control.
        '''</summary>
        Protected WithEvents btnRegister As Global.System.Web.UI.WebControls.Button

    End Class


